drop table if exists wd_staging;
CREATE TABLE wd_staging (
    "STATION" TEXT, "DATE" TEXT, "LATITUDE" TEXT, "LONGITUDE" TEXT, "ELEVATION" TEXT,
    "NAME" TEXT, "REPORT_TYPE" TEXT, "SOURCE" TEXT, "HourlyAltimeterSetting" TEXT,
    "HourlyDewPointTemperature" TEXT, "HourlyDryBulbTemperature" TEXT, "HourlyPrecipitation" TEXT,
    "HourlyPresentWeatherType" TEXT, "HourlyPressureChange" TEXT, "HourlyPressureTendency" TEXT,
    "HourlyRelativeHumidity" TEXT, "HourlySkyConditions" TEXT, "HourlySeaLevelPressure" TEXT,
    "HourlyStationPressure" TEXT, "HourlyVisibility" TEXT, "HourlyWetBulbTemperature" TEXT,
    "HourlyWindDirection" TEXT, "HourlyWindGustSpeed" TEXT, "HourlyWindSpeed" TEXT,
    "Sunrise" TEXT, "Sunset" TEXT, "DailyAverageDewPointTemperature" TEXT,
    "DailyAverageDryBulbTemperature" TEXT, "DailyAverageRelativeHumidity" TEXT,
    "DailyAverageSeaLevelPressure" TEXT, "DailyAverageStationPressure" TEXT,
    "DailyAverageWetBulbTemperature" TEXT, "DailyAverageWindSpeed" TEXT,
    "DailyCoolingDegreeDays" TEXT, "DailyDepartureFromNormalAverageTemperature" TEXT,
    "DailyHeatingDegreeDays" TEXT, "DailyMaximumDryBulbTemperature" TEXT,
    "DailyMinimumDryBulbTemperature" TEXT, "DailyPeakWindDirection" TEXT,
    "DailyPeakWindSpeed" TEXT, "DailyPrecipitation" TEXT, "DailySnowDepth" TEXT,
    "DailySnowfall" TEXT, "DailySustainedWindDirection" TEXT, "DailySustainedWindSpeed" TEXT,
    "DailyWeather" TEXT, "MonthlyAverageRH" TEXT, "MonthlyDaysWithGT001Precip" TEXT,
    "MonthlyDaysWithGT010Precip" TEXT, "MonthlyDaysWithGT32Temp" TEXT,
    "MonthlyDaysWithGT90Temp" TEXT, "MonthlyDaysWithLT0Temp" TEXT,
    "MonthlyDaysWithLT32Temp" TEXT, "MonthlyDepartureFromNormalAverageTemperature" TEXT,
    "MonthlyDepartureFromNormalCoolingDegreeDays" TEXT, "MonthlyDepartureFromNormalHeatingDegreeDays" TEXT,
    "MonthlyDepartureFromNormalMaximumTemperature" TEXT, "MonthlyDepartureFromNormalMinimumTemperature" TEXT,
    "MonthlyDepartureFromNormalPrecipitation" TEXT, "MonthlyDewpointTemperature" TEXT,
    "MonthlyGreatestPrecip" TEXT, "MonthlyGreatestPrecipDate" TEXT,
    "MonthlyGreatestSnowDepth" TEXT, "MonthlyGreatestSnowDepthDate" TEXT,
    "MonthlyGreatestSnowfall" TEXT, "MonthlyGreatestSnowfallDate" TEXT,
    "MonthlyMaxSeaLevelPressureValue" TEXT, "MonthlyMaxSeaLevelPressureValueDate" TEXT,
    "MonthlyMaxSeaLevelPressureValueTime" TEXT, "MonthlyMaximumTemperature" TEXT,
    "MonthlyMeanTemperature" TEXT, "MonthlyMinSeaLevelPressureValue" TEXT,
    "MonthlyMinSeaLevelPressureValueDate" TEXT, "MonthlyMinSeaLevelPressureValueTime" TEXT,
    "MonthlyMinimumTemperature" TEXT, "MonthlySeaLevelPressure" TEXT,
    "MonthlyStationPressure" TEXT, "MonthlyTotalLiquidPrecipitation" TEXT,
    "MonthlyTotalSnowfall" TEXT, "MonthlyWetBulb" TEXT, "AWND" TEXT, "CDSD" TEXT,
    "CLDD" TEXT, "DSNW" TEXT, "HDSD" TEXT, "HTDD" TEXT, "DYTS" TEXT, "DYHF" TEXT,
    "NormalsCoolingDegreeDay" TEXT, "NormalsHeatingDegreeDay" TEXT, "ShortDurationEndDate005" TEXT,
    "ShortDurationEndDate010" TEXT, "ShortDurationEndDate015" TEXT, "ShortDurationEndDate020" TEXT,
    "ShortDurationEndDate030" TEXT, "ShortDurationEndDate045" TEXT, "ShortDurationEndDate060" TEXT,
    "ShortDurationEndDate080" TEXT, "ShortDurationEndDate100" TEXT, "ShortDurationEndDate120" TEXT,
    "ShortDurationEndDate150" TEXT, "ShortDurationEndDate180" TEXT, "ShortDurationPrecipitationValue005" TEXT,
    "ShortDurationPrecipitationValue010" TEXT, "ShortDurationPrecipitationValue015" TEXT,
    "ShortDurationPrecipitationValue020" TEXT, "ShortDurationPrecipitationValue030" TEXT,
    "ShortDurationPrecipitationValue045" TEXT, "ShortDurationPrecipitationValue060" TEXT,
    "ShortDurationPrecipitationValue080" TEXT, "ShortDurationPrecipitationValue100" TEXT,
    "ShortDurationPrecipitationValue120" TEXT, "ShortDurationPrecipitationValue150" TEXT,
    "ShortDurationPrecipitationValue180" TEXT, "REM" TEXT, "BackupDirection" TEXT,
    "BackupDistance" TEXT, "BackupDistanceUnit" TEXT, "BackupElements" TEXT,
    "BackupElevation" TEXT, "BackupEquipment" TEXT, "BackupLatitude" TEXT,
    "BackupLongitude" TEXT, "BackupName" TEXT, "WindEquipmentChangeDate" TEXT
);

-- newer postgres COPY command has on ON_ERROR argument
-- to just swallow row errors and keep importing anyways
-- here we're stuck with failing the entire csv-copy
-- the failure is atomic, which is great for real-world use cases
-- but terrible for my personal case of just messing around :)
COPY wd_staging FROM :'filename' WITH (FORMAT CSV, HEADER);

INSERT INTO wd (
    "STATION", "DATE", "LATITUDE", "LONGITUDE", "ELEVATION", "NAME", "REPORT_TYPE", "SOURCE",
    "HourlyAltimeterSetting", "HourlyDewPointTemperature", "HourlyDryBulbTemperature", "HourlyPrecipitation",
    "HourlyPresentWeatherType", "HourlyPressureChange", "HourlyPressureTendency", "HourlyRelativeHumidity",
    "HourlySkyConditions", "HourlySeaLevelPressure", "HourlyStationPressure", "HourlyVisibility",
    "HourlyWetBulbTemperature", "HourlyWindDirection", "HourlyWindGustSpeed", "HourlyWindSpeed",
    "Sunrise", "Sunset", "DailyAverageDewPointTemperature", "DailyAverageDryBulbTemperature",
    "DailyAverageRelativeHumidity", "DailyAverageSeaLevelPressure", "DailyAverageStationPressure",
    "DailyAverageWetBulbTemperature", "DailyAverageWindSpeed", "DailyCoolingDegreeDays",
    "DailyDepartureFromNormalAverageTemperature", "DailyHeatingDegreeDays", "DailyMaximumDryBulbTemperature",
    "DailyMinimumDryBulbTemperature", "DailyPeakWindDirection", "DailyPeakWindSpeed", "DailyPrecipitation",
    "DailySnowDepth", "DailySnowfall", "DailySustainedWindDirection", "DailySustainedWindSpeed",
    "DailyWeather", "MonthlyAverageRH", "MonthlyDaysWithGT001Precip", "MonthlyDaysWithGT010Precip",
    "MonthlyDaysWithGT32Temp", "MonthlyDaysWithGT90Temp", "MonthlyDaysWithLT0Temp", "MonthlyDaysWithLT32Temp",
    "MonthlyDepartureFromNormalAverageTemperature", "MonthlyDepartureFromNormalCoolingDegreeDays",
    "MonthlyDepartureFromNormalHeatingDegreeDays", "MonthlyDepartureFromNormalMaximumTemperature",
    "MonthlyDepartureFromNormalMinimumTemperature", "MonthlyDepartureFromNormalPrecipitation",
    "MonthlyDewpointTemperature", "MonthlyGreatestPrecip", "MonthlyGreatestPrecipDate",
    "MonthlyGreatestSnowDepth", "MonthlyGreatestSnowDepthDate", "MonthlyGreatestSnowfall",
    "MonthlyGreatestSnowfallDate", "MonthlyMaxSeaLevelPressureValue", "MonthlyMaxSeaLevelPressureValueDate",
    "MonthlyMaxSeaLevelPressureValueTime", "MonthlyMaximumTemperature", "MonthlyMeanTemperature",
    "MonthlyMinSeaLevelPressureValue", "MonthlyMinSeaLevelPressureValueDate", "MonthlyMinSeaLevelPressureValueTime",
    "MonthlyMinimumTemperature", "MonthlySeaLevelPressure", "MonthlyStationPressure",
    "MonthlyTotalLiquidPrecipitation", "MonthlyTotalSnowfall", "MonthlyWetBulb", "AWND", "CDSD", "CLDD",
    "DSNW", "HDSD", "HTDD", "DYTS", "DYHF", "NormalsCoolingDegreeDay", "NormalsHeatingDegreeDay",
    "ShortDurationEndDate005", "ShortDurationEndDate010", "ShortDurationEndDate015", "ShortDurationEndDate020",
    "ShortDurationEndDate030", "ShortDurationEndDate045", "ShortDurationEndDate060", "ShortDurationEndDate080",
    "ShortDurationEndDate100", "ShortDurationEndDate120", "ShortDurationEndDate150", "ShortDurationEndDate180",
    "ShortDurationPrecipitationValue005", "ShortDurationPrecipitationValue010", "ShortDurationPrecipitationValue015",
    "ShortDurationPrecipitationValue020", "ShortDurationPrecipitationValue030", "ShortDurationPrecipitationValue045",
    "ShortDurationPrecipitationValue060", "ShortDurationPrecipitationValue080", "ShortDurationPrecipitationValue100",
    "ShortDurationPrecipitationValue120", "ShortDurationPrecipitationValue150", "ShortDurationPrecipitationValue180",
    "REM", "BackupDirection", "BackupDistance", "BackupDistanceUnit", "BackupElements", "BackupElevation",
    "BackupEquipment", "BackupLatitude", "BackupLongitude", "BackupName", "WindEquipmentChangeDate"
)
SELECT 
    -- Primary Keys & Core Metadata
    "STATION"::BIGINT,
    "DATE"::TIMESTAMP,
    NULLIF(TRIM("LATITUDE"), '')::NUMERIC(9,6),
    NULLIF(TRIM("LONGITUDE"), '')::NUMERIC(9,6),
    NULLIF(TRIM("ELEVATION"), '')::NUMERIC(6,2),
    "NAME",
    "REPORT_TYPE",
    "SOURCE",
    
    -- Hourly Metrics
    NULLIF(TRIM("HourlyAltimeterSetting"), '')::NUMERIC(5,2),
    NULLIF(TRIM("HourlyDewPointTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("HourlyDryBulbTemperature"), '')::NUMERIC(5,1),
    "HourlyPrecipitation", -- Stored as VARCHAR to natively support 'T' (Trace) records
    "HourlyPresentWeatherType",
    "HourlyPressureChange",
    NULLIF(TRIM("HourlyPressureTendency"), '')::INTEGER,
    NULLIF(TRIM("HourlyRelativeHumidity"), '')::INTEGER,
    "HourlySkyConditions",
    NULLIF(TRIM("HourlySeaLevelPressure"), '')::NUMERIC(5,2),
    NULLIF(TRIM("HourlyStationPressure"), '')::NUMERIC(5,2),
    NULLIF(TRIM("HourlyVisibility"), '')::NUMERIC(5,2),
    NULLIF(TRIM("HourlyWetBulbTemperature"), '')::NUMERIC(5,1),
    "HourlyWindDirection",
    NULLIF(TRIM("HourlyWindGustSpeed"), '')::INTEGER,
    NULLIF(TRIM("HourlyWindSpeed"), '')::INTEGER,
    "Sunrise",
    "Sunset",
    
    -- Daily Aggregations
    NULLIF(TRIM("DailyAverageDewPointTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("DailyAverageDryBulbTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("DailyAverageRelativeHumidity"), '')::INTEGER,
    NULLIF(TRIM("DailyAverageSeaLevelPressure"), '')::NUMERIC(5,2),
    NULLIF(TRIM("DailyAverageStationPressure"), '')::NUMERIC(5,2),
    NULLIF(TRIM("DailyAverageWetBulbTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("DailyAverageWindSpeed"), '')::NUMERIC(4,1),
    NULLIF(TRIM("DailyCoolingDegreeDays"), '')::INTEGER,
    NULLIF(TRIM("DailyDepartureFromNormalAverageTemperature"), '')::NUMERIC(4,1),
    NULLIF(TRIM("DailyHeatingDegreeDays"), '')::INTEGER,
    NULLIF(TRIM("DailyMaximumDryBulbTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("DailyMinimumDryBulbTemperature"), '')::NUMERIC(5,1),
    "DailyPeakWindDirection",
    NULLIF(TRIM("DailyPeakWindSpeed"), '')::INTEGER,
    "DailyPrecipitation",
    "DailySnowDepth",
    "DailySnowfall",
    "DailySustainedWindDirection",
    NULLIF(TRIM("DailySustainedWindSpeed"), '')::INTEGER,
    "DailyWeather",
    
    -- Monthly Aggregations
    NULLIF(TRIM("MonthlyAverageRH"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDaysWithGT001Precip"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDaysWithGT010Precip"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDaysWithGT32Temp"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDaysWithGT90Temp"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDaysWithLT0Temp"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDaysWithLT32Temp"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDepartureFromNormalAverageTemperature"), '')::NUMERIC(4,1),
    NULLIF(TRIM("MonthlyDepartureFromNormalCoolingDegreeDays"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDepartureFromNormalHeatingDegreeDays"), '')::INTEGER,
    NULLIF(TRIM("MonthlyDepartureFromNormalMaximumTemperature"), '')::NUMERIC(4,1),
    NULLIF(TRIM("MonthlyDepartureFromNormalMinimumTemperature"), '')::NUMERIC(4,1),
    NULLIF(TRIM("MonthlyDepartureFromNormalPrecipitation"), '')::NUMERIC(5,2),
    NULLIF(TRIM("MonthlyDewpointTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("MonthlyGreatestPrecip"), '')::NUMERIC(5,2),
    "MonthlyGreatestPrecipDate",
    "MonthlyGreatestSnowDepth",
    "MonthlyGreatestSnowDepthDate",
    "MonthlyGreatestSnowfall",
    "MonthlyGreatestSnowfallDate",
    NULLIF(TRIM("MonthlyMaxSeaLevelPressureValue"), '')::NUMERIC(5,2),
    "MonthlyMaxSeaLevelPressureValueDate",
    "MonthlyMaxSeaLevelPressureValueTime",
    NULLIF(TRIM("MonthlyMaximumTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("MonthlyMeanTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("MonthlyMinSeaLevelPressureValue"), '')::NUMERIC(5,2),
    "MonthlyMinSeaLevelPressureValueDate",
    "MonthlyMinSeaLevelPressureValueTime",
    NULLIF(TRIM("MonthlyMinimumTemperature"), '')::NUMERIC(5,1),
    NULLIF(TRIM("MonthlySeaLevelPressure"), '')::NUMERIC(5,2),
    NULLIF(TRIM("MonthlyStationPressure"), '')::NUMERIC(5,2),
    NULLIF(TRIM("MonthlyTotalLiquidPrecipitation"), '')::NUMERIC(5,2),
    NULLIF(TRIM("MonthlyTotalSnowfall"), '')::NUMERIC(5,1),
    NULLIF(TRIM("MonthlyWetBulb"), '')::NUMERIC(5,1),
    
    -- Climatological Indexes (AWND, Degree Days, etc.)
    NULLIF(TRIM("AWND"), '')::NUMERIC(4,1),
    NULLIF(TRIM("CDSD"), '')::INTEGER,
    NULLIF(TRIM("CLDD"), '')::INTEGER,
    NULLIF(TRIM("DSNW"), '')::INTEGER,
    NULLIF(TRIM("HDSD"), '')::INTEGER,
    NULLIF(TRIM("HTDD"), '')::INTEGER,
    NULLIF(TRIM("DYTS"), '')::INTEGER,
    NULLIF(TRIM("DYHF"), '')::INTEGER,
    NULLIF(TRIM("NormalsCoolingDegreeDay"), '')::INTEGER,
    NULLIF(TRIM("NormalsHeatingDegreeDay"), '')::INTEGER,
    
    -- Short Duration End Dates
    "ShortDurationEndDate005", "ShortDurationEndDate010", "ShortDurationEndDate015", "ShortDurationEndDate020",
    "ShortDurationEndDate030", "ShortDurationEndDate045", "ShortDurationEndDate060", "ShortDurationEndDate080",
    "ShortDurationEndDate100", "ShortDurationEndDate120", "ShortDurationEndDate150", "ShortDurationEndDate180",
    
    -- Short Duration Precipitation Values
    NULLIF(TRIM("ShortDurationPrecipitationValue005"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue010"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue015"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue020"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue030"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue045"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue060"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue080"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue100"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue120"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue150"), '')::NUMERIC(5,2),
    NULLIF(TRIM("ShortDurationPrecipitationValue180"), '')::NUMERIC(5,2),
    
    -- Remarks & Station Backup metadata
    "REM",
    "BackupDirection",
    NULLIF(TRIM("BackupDistance"), '')::NUMERIC(5,2),
    "BackupDistanceUnit",
    "BackupElements",
    NULLIF(TRIM("BackupElevation"), '')::NUMERIC(6,2),
    "BackupEquipment",
    NULLIF(TRIM("BackupLatitude"), '')::NUMERIC(9,6),
    NULLIF(TRIM("BackupLongitude"), '')::NUMERIC(9,6),
    "BackupName",
    NULLIF(TRIM("WindEquipmentChangeDate"), '')::DATE
FROM wd_staging;


